In [ ]:
#Action function
class CustomActionSpace:
    def _init_(self, mask, M, K, B):
        """
        Initialize the custom action space.
        
        Parameters:
        - mask: Binary matrix (M x B) (note : should be K x B) where 0 indicates the action must be 0.
        - M: Maximum value for valid actions (actions range from 0 to M-1).
        - K : number of eMBB users
        """
        self.mask = np.array(mask)  # Ensure the mask is a NumPy array
        self.M = M
        self.K = K
        self.B = B
        
        # Define a MultiDiscrete space where valid actions can be adjusted later
        self.action_space = MultiDiscrete([M] * self.B)
    
    def sample(self):
        """
        Generate a valid action that adheres to the mask constraints.
        """
        # Initialize an empty action array
        action = np.zeros_like(self.mask, dtype=int)
        
        # Iterate over each position in the mask
        for i in range(self.mask.shape[0]):  # Rows
            for j in range(self.mask.shape[1]):  # Columns
                if self.mask[i, j] == 1:
                    # If mask allows action, sample a value in [0, M-1]
                    action[i, j] = np.random.randint(0, self.M)
                else:
                    # If mask disallows action, set it to 0
                    action[i, j] = 0
        return action

var = CustomActionSpace(x,M,K,B)
print(var.action_space)
print(var.sample())

In [3]:
import random
import numpy as np

def allocate_round_robin_matrix(n_users, n_rbs):
    """
    Allocates resource blocks to users using a round-robin approach and returns
    the allocation matrix.

    Args:
        n_users (int): The number of users (rows in the matrix).
        n_rbs (int): The number of resource blocks (columns in the matrix).

    Returns:
        numpy.ndarray: An allocation matrix of shape (n_users, n_rbs) where
                       matrix[i, j] = 1 if user i is allocated resource block j,
                       and 0 otherwise.
    """
    allocation_matrix = np.zeros((n_users, n_rbs), dtype=int)
    rb_index = 0
    while rb_index < n_rbs:
        user_index = rb_index % n_users
        allocation_matrix[user_index, rb_index] = 1
        rb_index += 1
    return allocation_matrix

print(allocate_round_robin_matrix(5, 12))

[[1 0 0 0 0 1 0 0 0 0 1 0]
 [0 1 0 0 0 0 1 0 0 0 0 1]
 [0 0 1 0 0 0 0 1 0 0 0 0]
 [0 0 0 1 0 0 0 0 1 0 0 0]
 [0 0 0 0 1 0 0 0 0 1 0 0]]


In [ ]:
import numpy as np

class Dataset:
	def __init__(self):
		self.data = np.array([[1, 0, 1], [0, 1, 0], [0, 0, 0]])
		self.last_action = (0, 0, None)

	def perform_action(self, agent_action) -> bool:
        # Iterate over each position in the rb_user_martrix to allocate the resources
		for i in range(self.last_action[0], self.data.shape[0]):  # Rows
			for j in range(self.last_action[1], self.data.shape[1]):  # Columns
				if self.data[i, j] != 0:
					# If mask allows action, sample a value in [0, M-1]
					self.data[i][j] = agent_action
					self.last_action = (i, j + 1, agent_action)
					return
				else:
					continue

		while()

if __name__=="__main__":
	model = Dataset()

	model.perform_action(10)
	print(model.data)

	model.perform_action(12)
	print(model.data)

	model.perform_action(14)
	print(model.data)

[[10  0  1]
 [ 0  1  0]
 [ 0  0  0]]
[[10  0 12]
 [ 0  1  0]
 [ 0  0  0]]
[[10  0 12]
 [ 0  1  0]
 [ 0  0  0]]


In [ ]:
import numpy as np

class Dataset:
	def __init__(self):
		self.data = np.array([[1, 0, 1], [0, 1, 0], [0, 0, 0]])
		self.last_action = (0, 0, None)

	def perform_action(self, agent_action) -> bool:

		# while()
				

				



if __name__=="__main__":
	model = Dataset()

	model.perform_action(10)
	print(model.data)

	model.perform_action(12)
	print(model.data)

	model.perform_action(14)
	print(model.data)

In [ ]:
import numpy as np

array = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
size = (array.shape[0] * array.shape[1])

i = 0
j = 0

index = (i + j + 1) % size

i = int(index / array.shape[0])
j = index % array.shape[0]

while(array[i][j] != 0):
    array[i][j] = random.randint(1, 5)


print(i, j)

2 0


In [11]:
import random

def display(matrix):
    for i in matrix:
        print(i)

class RBAllocator:   
    def __init__(self, K, B, M):
        self.K = K  # number of users (rows)
        self.B = B  # number of RBs (columns)
        self.M = M  # upper bound for random values (1..M-1)
        
        # Initialize the matrix: K x B, with each column having exactly one 1 (rest zeros)
        self.matrix = [[0 for _ in range(B)] for _ in range(K)]
        
        if K == B:
            # Create a permutation matrix (each row and column has exactly one 1)
            cols = random.sample(range(B), B)
            for row in range(K):
                self.matrix[row][cols[row]] = 1
        else:
            # Randomly assign each column to a row (some rows may have multiple 1's if K < B)
            for col in range(B):
                row = random.randint(0, K-1)
                self.matrix[row][col] = 1
        
        self.current_pos = (0, 0)  # (row, column), starts at (0,0)
    
    def update_matrix(self):
        rows = self.K
        cols = self.B
        i, j = self.current_pos
        
        found = False
        for _ in range(rows * cols):
            # Check current position
            if self.matrix[i][j] != 0:
                # Replace with random value in [1, M-1]
                new_val = random.randint(1, self.M - 1)
                self.matrix[i][j] = new_val
                found = True
            
            # Move to next position (row-major order)
            j += 1
            if j >= cols:
                j = 0
                i += 1
                if i >= rows:
                    i = 0
            
            if found:
                break
        
        # Update the next starting position
        self.current_pos = (i, j)
        
        return self.matrix
    
allocator = RBAllocator(5, 6, 7)

display(allocator.matrix)

[0, 0, 1, 0, 0, 0]
[0, 0, 0, 0, 0, 0]
[0, 1, 0, 0, 1, 0]
[0, 0, 0, 1, 0, 0]
[1, 0, 0, 0, 0, 1]


In [16]:
import random

def display(matrix):
    for i in matrix:
        print(i)

class RBAllocator:
    def __init__(self, K, B, M):
        self.K = K  # number of users (rows)
        self.B = B  # number of RBs (columns)
        self.M = M  # upper bound for random values (1..M-1)
        
        # Initialize the matrix: K x B, with each column having exactly one 1 (rest zeros)
        self.matrix = [[0 for _ in range(B)] for _ in range(K)]
        
        if K == B:
            # Create a permutation matrix (each row and column has exactly one 1)
            cols = random.sample(range(B), B)
            for row in range(K):
                self.matrix[row][cols[row]] = 1
        elif K < B:
            # Ensure each row has at least one 1, and each column has exactly one 1
            # First, assign one 1 to each row to satisfy the row constraint
            cols = random.sample(range(B), K)  # Select K columns randomly
            for row in range(K):
                self.matrix[row][cols[row]] = 1
            # Assign remaining B-K columns to rows randomly
            remaining_cols = [j for j in range(B) if j not in cols]
            for col in remaining_cols:
                row = random.randint(0, K-1)
                self.matrix[row][col] = 1
        else:  # K > B
            # Ensure each row has at most one 1, and each column has exactly one 1
            # Randomly assign each column to a unique row
            rows = random.sample(range(K), B)  # Select B rows randomly
            for col in range(B):
                self.matrix[rows[col]][col] = 1
        
        print("Initial matrix:")
        for row in self.matrix:
            print(row)
        self.current_pos = (0, 0)  # (row, column), starts at (0,0)
    
    def update_matrix(self):
        rows = self.K
        cols = self.B
        i, j = self.current_pos
        
        found = False
        for _ in range(rows * cols):
            # Check current position
            if self.matrix[i][j] != 0:
                # Replace with random value in [1, M-1]
                new_val = random.randint(1, self.M - 1)
                self.matrix[i][j] = new_val
                found = True
            
            # Move to next position (row-major order)
            j += 1
            if j >= cols:
                j = 0
                i += 1
                if i >= rows:
                    i = 0
            
            if found:
                break
        
        # Update the next starting position
        self.current_pos = (i, j)
        
        return self.matrix
    
allocator = RBAllocator(5, 4, 7)
print()
display(allocator.matrix)

Initial matrix:
[0, 0, 0, 1]
[0, 0, 1, 0]
[0, 0, 0, 0]
[1, 0, 0, 0]
[0, 1, 0, 0]

[0, 0, 0, 1]
[0, 0, 1, 0]
[0, 0, 0, 0]
[1, 0, 0, 0]
[0, 1, 0, 0]


In [ ]:
self.K = K  # number of users (rows)
self.B = B  # number of RBs (columns)
self.M = M  # upper bound for random values (1..M-1)

# Initialize the matrix: K x B, with each column having exactly one 1 (rest zeros)
self.matrix = [[0 for _ in range(B)] for _ in range(K)]

if K == B:
    # Create a permutation matrix (each row and column has exactly one 1)
    cols = random.sample(range(B), B)
    for row in range(K):
        self.matrix[row][cols[row]] = 1
elif K < B:
    # Ensure each row has at least one 1, and each column has exactly one 1
    # First, assign one 1 to each row to satisfy the row constraint
    cols = random.sample(range(B), K)  # Select K columns randomly
    for row in range(K):
        self.matrix[row][cols[row]] = 1
    # Assign remaining B-K columns to rows randomly
    remaining_cols = [j for j in range(B) if j not in cols]
    for col in remaining_cols:
        row = random.randint(0, K-1)
        self.matrix[row][col] = 1
else:  # K > B
    # Ensure each row has at most one 1, and each column has exactly one 1
    # Randomly assign each column to a unique row
    rows = random.sample(range(K), B)  # Select B rows randomly
    for col in range(B):
        self.matrix[rows[col]][col] = 1

print("Initial matrix:")
for row in self.matrix:
    print(row)
self.current_pos = (0, 0)  # (row, column), starts at (0,0)

In [32]:
from gymnasium.spaces import Box
import numpy as np

obs = Box(
    low = 0,
	high = 7,
	shape = (3, 4),
	dtype=np.int32
)

print(np.concatenate((obs.sample(), obs.sample())))

[[5 7 0 5]
 [1 6 3 1]
 [4 1 3 2]
 [0 5 2 7]
 [0 4 5 3]
 [5 5 5 2]]
