In [ ]:
#Action function
class CustomActionSpace:
    def _init_(self, mask, M, K, B):
        """
        Initialize the custom action space.
        
        Parameters:
        - mask: Binary matrix (M x B) (note : should be K x B) where 0 indicates the action must be 0.
        - M: Maximum value for valid actions (actions range from 0 to M-1).
        - K : number of eMBB users
        """
        self.mask = np.array(mask)  # Ensure the mask is a NumPy array
        self.M = M
        self.K = K
        self.B = B
        
        # Define a MultiDiscrete space where valid actions can be adjusted later
        self.action_space = MultiDiscrete([M] * self.B)
    
    def sample(self):
        """
        Generate a valid action that adheres to the mask constraints.
        """
        # Initialize an empty action array
        action = np.zeros_like(self.mask, dtype=int)
        
        # Iterate over each position in the mask
        for i in range(self.mask.shape[0]):  # Rows
            for j in range(self.mask.shape[1]):  # Columns
                if self.mask[i, j] == 1:
                    # If mask allows action, sample a value in [0, M-1]
                    action[i, j] = np.random.randint(0, self.M)
                else:
                    # If mask disallows action, set it to 0
                    action[i, j] = 0
        return action

var = CustomActionSpace(x,M,K,B)
print(var.action_space)
print(var.sample())

In [3]:
import random
import numpy as np

def allocate_round_robin_matrix(n_users, n_rbs):
    """
    Allocates resource blocks to users using a round-robin approach and returns
    the allocation matrix.

    Args:
        n_users (int): The number of users (rows in the matrix).
        n_rbs (int): The number of resource blocks (columns in the matrix).

    Returns:
        numpy.ndarray: An allocation matrix of shape (n_users, n_rbs) where
                       matrix[i, j] = 1 if user i is allocated resource block j,
                       and 0 otherwise.
    """
    allocation_matrix = np.zeros((n_users, n_rbs), dtype=int)
    rb_index = 0
    while rb_index < n_rbs:
        user_index = rb_index % n_users
        allocation_matrix[user_index, rb_index] = 1
        rb_index += 1
    return allocation_matrix

print(allocate_round_robin_matrix(5, 12))

[[1 0 0 0 0 1 0 0 0 0 1 0]
 [0 1 0 0 0 0 1 0 0 0 0 1]
 [0 0 1 0 0 0 0 1 0 0 0 0]
 [0 0 0 1 0 0 0 0 1 0 0 0]
 [0 0 0 0 1 0 0 0 0 1 0 0]]


In [ ]:
import numpy as np

class Dataset:
	def __init__(self):
		self.data = np.array([[1, 0, 1], [0, 1, 0], [0, 0, 0]])
		self.last_action = (0, 0, None)

	def perform_action(self, agent_action) -> bool:
        # Iterate over each position in the rb_user_martrix to allocate the resources
		for i in range(self.last_action[0], self.data.shape[0]):  # Rows
			for j in range(self.last_action[1], self.data.shape[1]):  # Columns
				if self.data[i, j] != 0:
					# If mask allows action, sample a value in [0, M-1]
					self.data[i][j] = agent_action
					self.last_action = (i, j + 1, agent_action)
					return
				else:
					continue

		while()

if __name__=="__main__":
	model = Dataset()

	model.perform_action(10)
	print(model.data)

	model.perform_action(12)
	print(model.data)

	model.perform_action(14)
	print(model.data)

[[10  0  1]
 [ 0  1  0]
 [ 0  0  0]]
[[10  0 12]
 [ 0  1  0]
 [ 0  0  0]]
[[10  0 12]
 [ 0  1  0]
 [ 0  0  0]]


In [ ]:
import numpy as np

class Dataset:
	def __init__(self):
		self.data = np.array([[1, 0, 1], [0, 1, 0], [0, 0, 0]])
		self.last_action = (0, 0, None)

	def perform_action(self, agent_action) -> bool:

		# while()
				

				



if __name__=="__main__":
	model = Dataset()

	model.perform_action(10)
	print(model.data)

	model.perform_action(12)
	print(model.data)

	model.perform_action(14)
	print(model.data)

In [ ]:
import numpy as np

array = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
size = (array.shape[0] * array.shape[1])

i = 0
j = 0

index = (i + j + 1) % size

i = int(index / array.shape[0])
j = index % array.shape[0]

while(array[i][j] != 0):
    array[i][j] = random.randint(1, 5)


print(i, j)

2 0
